PAI_APP/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.main import views as main_views  # Import the main app's views

from django.conf.urls import handler403, handler404, handler500
from apps.main.views import custom_403_view, custom_404_view, custom_500_view

handler403 = 'apps.main.views.custom_403_view'
handler404 = 'apps.main.views.custom_404_view'
handler500 = 'apps.main.views.custom_500_view'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),

     path('', main_views.dashboard_view, name='root_dashboard'),

    path('', include('apps.arduino_comm.urls', namespace='arduino_comm')),  # New app
]

apps/arduino_comm/urls.py
from django.urls import path
from . import views

app_name = 'arduino_comm'

urlpatterns = [
    path('receive/', views.receive_data, name='receive_data'),
    path('send/', views.send_command, name='send_command'),
    path('configure/', views.configure_sensor, name='configure_sensor'),
    path('control/', views.control_page, name='control_panel'),
    path('fetch/', views.fetch_sensor_data, name='fetch_sensor_data'),
    path('active_sensors/', views.active_sensors_page, name='active_sensors_page'),
    path('save_sensors/', views.save_sensors, name='save_sensors'),
    path('reset-sensors/', views.reset_sensors, name='reset_sensors'),

]

apps/main/urls.py
from django.urls import path
from . import views
from django.conf.urls import handler403, handler404, handler500


app_name = 'main'



handler403 = 'apps.main.views.custom_403_view'
handler404 = 'apps.main.views.custom_404_view'
handler500 = 'apps.main.views.custom_500_view'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('profile/', views.profile_view, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('settings/', views.settings_view, name='settings'),  
    
    path('sensor-data/', views.get_sensor_data, name='sensor_data'),
]

apps/main/models.py
from django.contrib.auth.models import AbstractUser
from bson.objectid import ObjectId

apps/main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise ValidationError("Parolele nu se potrivesc!")

        return cleaned_data

apps/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import LoginForm, RegisterForm
from django.contrib import messages
from django.contrib.auth import get_user_model
from pymongo import MongoClient
import random

# MongoDB connection
client = MongoClient("mongodb://localhost:27017/")
db = client["pai"]

User = get_user_model()

# Custom error views
def custom_403_view(request, exception=None):
    return render(request, '403.html', status=403)

def custom_404_view(request, exception=None):
    return render(request, '404.html', status=404)

def custom_500_view(request):
    return render(request, '500.html', status=500)

# Login view
def login_view(request):
    error = None
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:dashboard')  # Redirect to dashboard after login
        else:
            error = "Eroare la autentificare! Adaugați utilizatorul și parola primită!"
    
    return render(request, 'main/login.html', {'error': error})

# Register view
def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            
            # Create the new user
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()
            
            # Automatically log in the new user after registration
            login(request, user)
            return redirect('main:dashboard')  # Redirect to dashboard after registration
        else:
            messages.error(request, 'A apărut o eroare la înregistrare!')
    else:
        form = RegisterForm()

    return render(request, 'main/register.html', {'form': form})

# Dashboard view
@login_required
def dashboard_view(request):
    sensors = list(db["sensors"].find())  # Fetch all sensors
    active_sensors = [sensor for sensor in sensors if sensor.get("active", False)]
    
    # Group sensors by type and mode
    analog_outputs = [sensor for sensor in active_sensors if sensor["type"] == "output" and sensor["mode"] == "analog"]
    digital_outputs = [sensor for sensor in active_sensors if sensor["type"] == "output" and sensor["mode"] == "digital"]
    analog_inputs = [sensor for sensor in active_sensors if sensor["type"] == "input" and sensor["mode"] == "analog"]
    digital_inputs = [sensor for sensor in active_sensors if sensor["type"] == "input" and sensor["mode"] == "digital"]

    return render(request, 'main/dashboard.html', {
        "analog_outputs": analog_outputs,
        "digital_outputs": digital_outputs,
        "analog_inputs": analog_inputs,
        "digital_inputs": digital_inputs,
    })

# Get sensor data
def get_sensor_data(request):
    try:
        sensors = list(db["sensors"].find())
        data = {sensor["id"]: {
            "status": sensor["status"],
            "value": sensor["value"],
            "name": sensor["name"],  # Include name here
        } for sensor in sensors}
        return JsonResponse(data, safe=False)  # Explicitly return JSON
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)

# Profile view
@login_required
def profile_view(request):
    # Determine user type based on is_superuser flag
    user_type = "Administrator" if request.user.is_superuser else "Utilizator"
    
    # Generate random phone number
    phone_number = f"+40 7{random.randint(20, 39)} {random.randint(100, 999)} {random.randint(100, 999)}"
    
    # Full list of Romanian county capitals (cities)
    cities = [
        "Alba Iulia", "Arad", "Bacău", "Baia Mare", "Bistrița", "Botoșani", "Brașov", "Brăila", "București",
        "Buzău", "Călărași", "Cluj-Napoca", "Constanța", "Craiova", "Deva", "Drobeta-Turnu Severin", "Focșani",
        "Galați", "Giurgiu", "Iași", "Pitești", "Ploiești", "Oradea", "Reșița", "Satu Mare", "Sfântu Gheorghe",
        "Sibiu", "Slatina", "Slobozia", "Suceava", "Târgu Jiu", "Târgu Mureș", "Timișoara", "Tulcea", "Vaslui",
        "Vatra Dornei", "Zalău", "Râmnicu Vâlcea", "Bârlad", "Făgăraș"
    ]
    
    # Common Romanian street names
    street_names = [
        "Mihai Viteazul", "Unirii", "Eroilor", "Primăverii", "Libertății", "Victoriei", "Independenței", 
        "Stefan cel Mare", "Calea București", "Calea Clujului", "Florilor", "Păcii", "Traian", "Carpaților",
        "George Coșbuc", "Griviței", "Horea", "Iuliu Maniu", "Alexandru Ioan Cuza", "Petru Rareș", 
        "Barbu Ștefănescu Delavrancea", "Ion Creangă", "Nicolae Bălcescu", "Vasile Alecsandri", "Eminescu"
    ]
    
    # Generate random address
    street_number = random.randint(1, 500)  # Larger range of street numbers
    random_street = random.choice(street_names)
    random_city = random.choice(cities)
    address = f"Str. {random_street} {street_number}, {random_city}, România"
    
    # Mock subscription level
    subscriptions = ["Basic", "Standard", "Premium", "Pro"]
    subscription = random.choice(subscriptions)
    
    return render(request, 'main/profile.html', {
        "user_type": user_type,
        "additional_data": {
            "phone": phone_number,
            "address": address,
            "subscription": subscription
        }
    })

# Logout view
def logout_view(request):
    logout(request)
    return redirect('main:login')

# Settings view
def settings_view(request):
    return render(request, 'main/settings.html')

templates/main/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tablou de bord</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    {% load custom_filters %}

    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
</head>
<body class="dashboard-body">
    <div class="container-fluid dashboard-container">
        <div class="row">
            <!-- Sidebar -->
            <nav class="col-md-4 col-lg-2 d-md-block sidebar sidebar-navigation">
                <div class="sidebar-sticky">
                    <h4 class="text-center py-4 sidebar-title">Tablou de Bord</h4>
                    <ul class="nav flex-column sidebar-menu">
                        <li class="nav-item menu-item">
                            <a class="nav-link active menu-link" href="{% url 'main:dashboard' %}">
                                <i class="fa fa-home"></i> Acasă
                            </a>
                        </li>

                        <li class="nav-item menu-item">
                            <a class="nav-link menu-link" href="{% url 'main:profile' %}">
                                <i class="fa fa-user"></i> Profil
                            </a>
                        </li>

                        <li class="nav-item menu-item">
                            <a class="nav-link menu-link" href="{% url 'arduino_comm:active_sensors_page' %}">
                                <i class="fa fa-cog"></i> Setări
                            </a>
                        </li>

                        <li class="nav-item menu-item">
                            <a class="nav-link menu-link" href="{% url 'main:logout' %}">
                                <i class="fa fa-sign-out"></i> Deconectare
                            </a>
                        </li>

                        <li class="nav-item menu-item">
                            <br><br>
                            <h5 class="text-center">Stare Cont</h5>
                            <p class="text-15left"><strong>Abonament:</strong> Activ</p>
                            <p class="text-15left"><strong>Ultima Conectare:</strong> {{ request.user.last_login }}</p>
                            <p class="text-15left"><strong>Email:</strong> {{ request.user.email }}<br><br></p>
                        </li>

                        <li class="nav-item menu-item">
                            <h5 class="card-title text-center">Notificări</h5>
                            <p class="text-15left">Rămâneți la curent</p>
                            <ul class="list-unstyled notifications-list text-15left"></ul>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Main Content -->
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 main-content">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 main-header">
                    <h1 class="welcome-message">Bun venit, {{ request.user.username }}</h1>
                </div>

                <!-- Outputs Section -->
                <div class="outputs-section mt-4">
                    <!-- Analog Outputs Group -->
                    <h3 class="section-title">Utilități</h3>
                    <div class="analog-group">
                        <div class="row mb-4">
                            {% for sensor in analog_outputs %}
                                <div class="col-md-6 analog-output">
                                    <div class="card shadow-sm sensor-card analog-card" id="sensor-{{ sensor.id }}">
                                        <div class="card-body">
                                            <div class="d-flex justify-content-between align-items-center">
                                                <h5 class="card-title">{{ sensor.name }}</h5>
                                            </div>
                                            <div class="text-center">
                                                {% if sensor.id == 'sensor_3' %}
                                                    <span id="value-display-{{ sensor.id }}" class="analog-value-display big-gradient-text">
                                                        {% if sensor.value == 0 %}
                                                            OPRIT
                                                        {% else %}
                                                            {{ sensor.value|value_to_kelvin }}
                                                        {% endif %}
                                                    </span>
                                                {% elif sensor.id == 'sensor_4' %}
                                                    <span id="value-display-{{ sensor.id }}" class="analog-value-display big-gradient-text">
                                                        {% if sensor.value == 0 %}
                                                            OPRIT
                                                        {% else %}
                                                            {{ sensor.value|value_to_celsius }}
                                                        {% endif %}
                                                    </span>
                                                {% endif %}
                                            </div>
                                            <input type="range" class="analog-control analog-slider" 
                                                   min="0" max="255" 
                                                   value="{{ sensor.value }}" 
                                                   onchange="sendAnalogValue('{{ sensor.id }}', this.value)"
                                                   
                                                   >
                                            <div class="preset-buttons text-center mt-3">
                                                {% if sensor.id == 'sensor_3' %}
                                                    <button class="btn btn-secondary btn-sm" onclick="sendPresetValue('{{ sensor.id }}', 50)">DORMITOR</button>
                                                    <button class="btn btn-secondary btn-sm" onclick="sendPresetValue('{{ sensor.id }}', 128)">BIROU</button>
                                                    <button class="btn btn-secondary btn-sm" onclick="sendPresetValue('{{ sensor.id }}', 250)">ATELIER</button>
                                                    <button class="btn btn-secondary btn-sm" onclick="sendPresetValue('{{ sensor.id }}', 0)">OPRIT</button>
                                                {% elif sensor.id == 'sensor_4' %}
                                                    <button class="btn btn-secondary btn-sm" onclick="sendPresetValue('{{ sensor.id }}', 50)">RECE</button>
                                                    <button class="btn btn-secondary btn-sm" onclick="sendPresetValue('{{ sensor.id }}', 93)">OBISNUIT</button>
                                                    <button class="btn btn-secondary btn-sm" onclick="sendPresetValue('{{ sensor.id }}', 250)">FOARTE CALD</button>
                                                    <button class="btn btn-secondary btn-sm" onclick="sendPresetValue('{{ sensor.id }}', 0)">OPRIT</button>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% if forloop.counter|divisibleby:2 and not forloop.last %}
                                    </div><div class="row mb-4">
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                    <!-- Digital Outputs Group -->
                    <h3 class="section-title mt-4">Uși</h3>
                    <div class="digital-group">
                        <div class="row mb-4">
                            {% for sensor in digital_outputs %}

                                <div class="col-md-6 digital-output">
                                    <div class="card shadow-sm sensor-card digital-card" id="sensor-{{ sensor.id }}">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ sensor.name }}</h5>
                                            <div class="lock-icon-container">
                                                <i class="fa fa-lock lock-icon lock-invisible"></i>
                                            </div>
                                            <button class="btn btn-secondary digital-control high-button" onclick="sendDigitalCommand('{{ sensor.id }}', 'high')">BLOCHEAZĂ</button>
                                            <button class="btn btn-secondary digital-control low-button" onclick="sendDigitalCommand('{{ sensor.id }}', 'low')">DEBLOCHEAZĂ</button>
                                        </div>
                                    </div>
                                </div>
                                {% if forloop.counter|divisibleby:2 and not forloop.last %}
                                    </div><div class="row mb-4">
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                               <!-- Digital Inputs Section -->
               
                        {% for sensor in digital_inputs %}
                            
                                <div class="card shadow-sm lock-invisible"
                                     id="sensor-{{ sensor.id }}"
                                     {% if sensor.value == 1 %} 
                                     style="background-color: {% if sensor.id == 'sensor_9' %}blue{% elif sensor.id == 'sensor_8' %}orange{% endif %};"
                                     {% endif %}>
                                    <div class="card-body">
                                        <h5 class="card-title">Sensor {{ sensor.name }}</h5>
                                        <p><strong>Mode:</strong> Digital</p>
                                        <p><strong>Status:</strong> 
                                            <span class="{% if sensor.status == 'high' %}high{% else %}low{% endif %}">
                                                {{ sensor.status|title }}
                                            </span>
                                        </p>
                                    </div>
                                </div>
                           
                        {% endfor %}
              
                </div>
            </main>
        </div>
    </div>

    <!-- Load JS Files -->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script>
        const sendCommandUrl = "{% url 'arduino_comm:send_command' %}";
        const sensorDataUrl = "{% url 'main:sensor_data' %}";
        const csrfToken = "{{ csrf_token }}";
    </script>
    <script src="{% static 'js/dashboard.js' %}"></script>
</body>
</html>

templates/main/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Interfață de autentificare!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!-- Load Static Assets -->
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="{% static 'images/img-01.png' %}" alt="IMG">
                </div>

                <!-- Django Form -->
                <form method="post" class="login100-form validate-form">
                    {% csrf_token %}
                    <span class="login100-form-title">
                        Autentificare Proiect AIA
                    </span>

                    <!-- Username Field -->
                    <div class="wrap-input100 validate-input" data-validate="Introduce-ți un user valid, în cazul dvs. este medic">
                        <input class="input100" type="text" name="username" placeholder="Utilizator">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-user" aria-hidden="true"></i>
                        </span>
                    </div>

                    <!-- Password Field -->
                    <div class="wrap-input100 validate-input" data-validate="Parola introdusă este greșită!">
                        <input class="input100" type="password" name="password" placeholder="Parolă">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>

                    <!-- Login Button -->
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Autentificare
                        </button>
                    </div>

                    <!-- Error Message Display -->
                    {% if error %}
                    <div class="text-center p-t-12">
                        <span class="txt1" style="color: red;">
                            {{ error }}
                        </span>
                    </div>
                    {% endif %}

                    <!-- Register Link -->
                    <div class="text-center p-t-12">
                        <span class="txt1">
                            Nu ai un cont?
                        </span>
                        <a class="txt2" href="{% url 'main:register' %}">
                            Creează unul aici
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Load JS Files -->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/main/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tablou de Bord</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
</head>
<body class="dashboard-body">
    <div class="container-fluid dashboard-container">
        <div class="row">
            <!-- Sidebar -->
            <nav class="col-md-4 col-lg-2 d-md-block sidebar sidebar-navigation">
                <div class="sidebar-sticky">
                    <h4 class="text-center py-4 sidebar-title">Tablou de Bord</h4>
                    <ul class="nav flex-column sidebar-menu">
                        <li class="nav-item menu-item">
                            <a class="nav-link menu-link" href="{% url 'main:dashboard' %}">
                                <i class="fa fa-home"></i> Acasă
                            </a>
                        </li>
                        <li class="nav-item menu-item">
                            <a  class="nav-link active menu-link"href="{% url 'main:profile' %}">
                                <i class="fa fa-user"></i> Profil
                            </a>
                        </li>
                        <li class="nav-item menu-item">
                            <a class="nav-link menu-link" href="{% url 'arduino_comm:active_sensors_page' %}">
                                <i class="fa fa-cog"></i> Setări
                            </a>
                        </li>
                        <li class="nav-item menu-item">
                            <a class="nav-link menu-link" href="{% url 'main:logout' %}">
                                <i class="fa fa-sign-out"></i> Deconectare
                            </a>
                        </li>
                        <li class="nav-item menu-item">
                            <h5 class="text-center">Stare Cont</h5>
                            <p class="text-15left"><strong>Abonament:</strong> Activ</p>
                            <p class="text-15left"><strong>Ultima Conectare:</strong> Nov. 20, 2024, 7:17 p.m.</p>
                            <p class="text-15left"><strong>Email:</strong> test@email.com</p>
                        </li>
                        <li class="nav-item menu-item">
                            <h5 class="card-title text-center">Notificări</h5>
                            <p class="text-15left">Rămâneți la curent</p>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Main Content -->
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 main-content">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 main-header">
                    <h1 class="welcome-message">Profil Utilizator</h1>
                </div>

                <!-- Profile Content -->
<div>
    <div class="card shadow-sm profile-card bg-dark1">
        <div class="card-body ">
            
            <p class="info-profile1"><strong>Username:</strong> {{ request.user.username }}</p>
            <p class="info-profile1"><strong>Email:</strong> {{ request.user.email }}</p>
            <p class="info-profile1"><strong>Data inregistrarii:</strong> {{ request.user.date_joined|date:"d-m-Y" }}</p>
            <p class="info-profile1"><strong>Ultima Activitate:</strong> {{ request.user.last_login|date:"d-m-Y H:i:s" }}</p>
            <p class="info-profile1"><strong>Tip cont:</strong> {{ user_type }}</p>
            <p class="info-profile1"><strong>Telefon:</strong> {{ additional_data.phone }}</p>
            <p class="info-profile1"><strong>Adresă:</strong> {{ additional_data.address }}</p>
            <p class="info-profile1"><strong>Abonament:</strong> {{ additional_data.subscription }}</p>
        </div>
    </div>
</div>
            </main>
        </div>
    </div>

    <!-- Load JS Files -->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        });
    </script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>